<a href="https://colab.research.google.com/github/tmendonca28/pytorch-trial/blob/master/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
# Creating a 2D array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [4]:
# Converting the array to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [0]:
import torch

In [6]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [7]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [9]:
np.random.rand(2, 2)

array([[0.77211032, 0.4759773 ],
       [0.80745397, 0.99166795]])

In [10]:
torch.rand(2, 2)

tensor([[0.7983, 0.5452],
        [0.5207, 0.4981]])

# **Seed for Reproducibility**

In [11]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

 **Note we get the exact same numbers when seed is 0**

In [13]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [14]:
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [15]:
# Torch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

Reproducibility is important; It allows us to have the same representation and hence produce reproducible experiments.
If we use a GPU we set the seed as follows:

torch.cuda.manual_seed_all(0)

# NumPy To Torch

In [17]:
# Numpy to torch
np_array = np.ones((2, 2))
print(np_array)

[[1. 1.]
 [1. 1.]]


In [18]:
print(type(np_array))

<class 'numpy.ndarray'>


In [19]:
# Converting to torch tensor
torch_tensor = torch.from_numpy(np_array)
print(type(torch_tensor))

<class 'torch.Tensor'>


In [20]:
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

# Torch to Numpy

In [21]:
torch_tensor = torch.ones(2, 2)
type(torch_tensor)

torch.Tensor

In [22]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

# GPU and CPU toggling

In [0]:
# CPU; by default
tensor_cpu = torch.ones(2, 2)

In [0]:
# CPU to GPU
if torch.cuda.is_available():
  tensor_cpu.cuda()

In [25]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

# Basic Math Tensor Operations

 **Resizing**

In [26]:
a = torch.ones(2, 2)
print(a.size())

torch.Size([2, 2])


In [27]:
a.view(4)

tensor([1., 1., 1., 1.])

**Element-wise addition**

In [28]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [29]:
b = torch.ones(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [30]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


**In-place addition**

In [31]:
print('Old c tensor')
print(c)

# _ implies in-place operations
c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


**Element-wise Subtraction**

In [32]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [33]:
a - b

tensor([[0., 0.],
        [0., 0.]])

In [34]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [35]:
# In-place
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


**Multiplication**

In [40]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

a*b

tensor([[0., 0.],
        [0., 0.]])

In [42]:
# Not in-place
print(torch.mul(a, b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [43]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


**The same goes for division**

# Tensor Mean

In [44]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [46]:
a.mean(dim=0)

tensor(5.5000)

In [47]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.shape

torch.Size([2, 10])

In [54]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

# Tensor Standard Deviation

In [56]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)