In [1]:
# First I need to import PyTorch
import torch

In [2]:
def activation(x):
    """
        Sigmoid activation function
        
        Arguments
        -----------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
# Generating some data
torch.manual_seed(7) # Setting the random seed so things will be predictable
# Features are 5 random variables
features = torch.randn((1,5))
# True weights for our data, random normal variables as well
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1,1))

In [4]:
print (features)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])


In [5]:
print (weights)

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


In [6]:
print(bias)

tensor([[0.3177]])


In [7]:
## Calculating the output of this network using the weights and bias tensors
output = activation(torch.sum(features*weights)+bias)
print(output)

tensor([[0.1595]])
