<a href="https://colab.research.google.com/github/tmendonca28/pytorch-trial/blob/master/Variables_and_Gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Variables


*   Variables are used to wrap a Tensor
*   Allows accumulation of gradients; main difference between a Variable and Tensor



In [0]:
import torch
from torch.autograd import Variable

In [6]:
a = Variable(torch.ones(2, 2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
# Not a variable
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [10]:
# Notice that a variable behaves quite similar to a tensor
b = Variable(torch.ones(2, 2), requires_grad=True)
b

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [11]:
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [12]:
print(a*b)
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


# Gradients

**What does requires_grad mean?**
* It allows for the calculation of gradients w.r.t. the variable

In [15]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [16]:
y = 5 * (x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

# Backward should only be called on a scalar (1-element tensor) or with gradient w.r.t the variable


*   Reducing y to a scalar...


In [19]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [30]:
# o.backward
x.grad

tensor([10., 10.])